cseweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('form.urls'))
]

form/urls.py
from django.urls import path
from .views import CheckView, OpenView, EventView, DownloadData, Blog

app_name = 'form'
urlpatterns = [
    path('', OpenView.as_view(), name='homepage'),
    path('reg', CheckView.as_view(), name='register'),
    path('eve', EventView.as_view(), name='event'),
    path('datadownload', DownloadData.as_view(), name='download'),
    path('blog', Blog.as_view(), name='blog'),
]

form/models.py
# Create your models here.
import datetime

from django.db import models
from django.utils.timezone import now


# Event Models
class AvailableFeatures(models.Model):
    feature_name = models.CharField(max_length=50, blank=False, null=False)
    current_status = models.BooleanField(default=True)

    def __str__(self):
        return self.feature_name


class Event(models.Model):
    event_name = models.CharField(max_length=100, blank=False)
    current_status = models.BooleanField(default=True)
    event_code = models.CharField(max_length=10, blank=False)
    event_venue = models.CharField(max_length=100,blank=True)
    description = models.TextField(blank=True)
    drive_link = models.CharField(max_length=300, blank=True)
    winner = models.CharField(max_length=250, blank=True)
    first_runner = models.CharField(max_length=250, blank=True)
    second_runner = models.CharField(max_length=250, blank=True)
    pub_date = models.DateTimeField(default=now())
    warn = models.CharField(max_length=250, blank=True)

    def __str__(self):
        return self.event_name

    def was_published_recently(self):
        return self.pub_date > now - datetime.timedelta(days=1)


# Branch Model
class Branch(models.Model):
    branch_name = models.CharField(max_length=100, primary_key=True)
    abbr = models.CharField(max_length=3)

    def __str__(self):
        return self.branch_name


# Student Information Model
class Student(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    student_name = models.CharField(max_length=200, blank=False)
    email_id = models.EmailField(max_length=70, blank=False)
    mobile_number = models.CharField(max_length=10, blank=False)
    roll_no = models.CharField(max_length=15, blank=False)
    branch = models.ForeignKey(Branch, on_delete=models.CASCADE)

    def __str__(self):
        return self.student_name


class Blog(models.Model):
    student_name = models.CharField(max_length=200, null=False, blank=False)
    roll_no = models.CharField(max_length=15, null=False)
    subject = models.CharField(max_length=200, null=False)
    suggestion = models.TextField(null=False)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.student_name

form/forms.py
from django.forms import ModelForm
from django import forms

from .models import Blog


class BlogForm(ModelForm):
    class Meta:
        model = Blog
        fields = ('student_name', 'roll_no', 'subject', 'suggestion')
        widgets = {
            'student_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': "Student Name", 'title': "Enter Student Name",
                       'required': "True"}),
            'roll_no': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Roll No", 'pattern': "[0-9]{10}",
                                              'title': "Enter Roll No.", 'required': "True"}),
            'subject': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': "Subject", 'title': "Enter Suggestion Subject",
                       'required': "True"}),
            'suggestion': forms.Textarea(
                attrs={'class': 'form-control', 'placeholder': "Enter Suggestion Or Query .....................", 'title': "Input Suggestion",
                       'required': "True", 'style': "resize: none;height: 200px;"})
        }

form/views.py
# Create your views here.
import csv
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import redirect, render
from .models import Event, Student, Branch
from django.views import View
from .forms import BlogForm
from django.core.mail import send_mail


# Create your views here.
# homepage view
class OpenView(View):
    def get(self, request):
        for i in Event.objects.filter(current_status=True):
            if i.warn:
                b = True
                break
        else:
            b = False
        if len(Event.objects.filter(current_status=True)) == 0:
            b = False
        return render(request, 'form/HomePage.html', {'error': Event.objects.filter(current_status=True), 'status': b})


# Register View
class CheckView(View):
    def get(self, request):
        msg = request.session.get('msg', False)
        if msg: del (request.session['msg'])
        context = {'event': Event.objects.all(), 'branch': Branch.objects.all(), 'error': msg}
        return render(request, 'form/register.html', context)

    def post(self, request):
        event = request.POST.get('event')
        student_name = request.POST.get('student_name')
        email_id = request.POST.get('email_p')
        mobile_number = request.POST.get('mobile_number')
        roll_no = request.POST.get('roll_no')
        branch = request.POST.get('branch')
        e = Event.objects.filter(current_status=True)
        a = Student.objects.filter(roll_no=roll_no.strip(), event__current_status=True)
        if len(a) == 0:
            s = Student(event=e.get(event_name=event), student_name=student_name, email_id=email_id.strip(),
                        mobile_number=mobile_number, roll_no=roll_no, branch=Branch.objects.get(branch_name=branch))
            s.save()
            message = send_mail("Successfully Registered for Event",
                                "You Have been Successfully Registered for " + e.get(
                                    event_name=event).event_name + " \n" + "Event Timing :" +
                                str(e.get(
                                    event_name=event).pub_date.date()) + " " + str(e.get(
                                    event_name=event).pub_date.time()) + "\nEvent Venue: " + e.get(
                                    event_name=event).event_venue + "\nIf any detail is missing in this mail feel "
                                                                    "free to contect us.",
                                "shia.sharma123@gmail.com", [email_id], fail_silently=False)
            if (message):
                request.session['msg'] = "We have sent you a mail"
            else:
                request.session['msg'] = "Student has Registered Successfully"
            return redirect(request.path)
        else:
            for i in a:
                if i.event.event_name == event.strip():
                    b = True
                    break
            else:
                b = False
            if b:
                request.session['msg'] = "Student has Already Registered for the Event"
                return redirect(request.path)
            else:
                s = Student(event=e.get(event_name=event), student_name=student_name, email_id=email_id.strip(),
                            mobile_number=mobile_number, roll_no=roll_no, branch=Branch.objects.get(branch_name=branch))
                s.save()
                message = send_mail("Successfully Registered for Event",
                                    "You Have been Successfully Registered for the " + e.get(event_name=event).event_name + "\n We want you to be present half hour before event will be started\n" + "Event Timing :" +str(e.get(event_name=event).pub_date.date())+" "+str(e.get(event_name=event).pub_date.time())+"\nEvent Venue: " + e.get(event_name=event).event_venue + "\nIf any detail is missing in this mail feel free to contect us.",
                                    "shia.sharma123@gmail.com", [email_id], fail_silently=False)
                if (message):
                    request.session['msg'] = "We have sent you a mail"
                else:
                    request.session['msg'] = "You have Registered For More than One Events"

                return redirect(request.path)


# Event Page View
class EventView(View):
    def get(self, request):
        context = {'event': Event.objects.all()}
        return render(request, 'form/eventdetail.html', context)


# Download Data In CSV Format
class DownloadData(View):
    def get(self, request):
        msg = request.session.get('msg', False)
        if msg: del (request.session['msg'])
        context = {'error': msg}
        return render(request, 'form/download.html', context)

    def post(self, request):
        code = request.POST['eve_code']
        response = HttpResponse(content_type='text/csv')
        writer = csv.writer(response)
        writer.writerow(['Event', 'Student Name', 'Email', 'Mobile No', 'Roll No', 'Branch'])
        a = Student.objects.filter(event__event_code=code.strip())
        if len(a) > 0:
            for stu in a.values_list('event__event_name',
                                     'student_name',
                                     'email_id',
                                     'mobile_number',
                                     'roll_no',
                                     'branch__abbr'):
                writer.writerow(stu)
            response['Content-Disposition'] = 'attachment;filename="data.csv"'
            return response
        else:
            request.session['msg'] = "No Event with this code Exist or No Data Available"
            return redirect(request.path)


# 404 Error Page Not Found View
def view_404(request, exception):
    return render(request, 'form/404.html')


class Blog(View):
    def get(self, request):
        msg = request.session.get('msg', False)
        form = BlogForm()
        if msg: del (request.session['msg'])
        context = {'form': form, 'message': msg}
        return render(request, 'form/blog.html', context)

    def post(self, request):
        form = BlogForm(request.POST)
        if form.is_valid():
            form.save()
            request.session['msg'] = "We Have Got Your Stand"
            return redirect(request.path)
        else:
            request.session['msg'] = "Try Again !"
            return redirect(request.path)

# Create your views here.

form/templates/form/HomePage.html
{% extends "form/base.html" %}
{% load static %}
{% block title %} Home{% endblock %}
{% block stysheet %}

    <link href='https://fonts.googleapis.com/css?family=Grandstander' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Aldrich' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/home.css' %}"> {% endblock %}
{% block style %}
{% if status %}
#marquee
{
    display:visible;
}
{% else %}
#marquee
{
    display:none;
}
{% endif %}
{% endblock %}
{% block nav %}
    <nav class="navbar navbar-expand-md fixed-top navbar-dark" style="background: #181818 !important;">
{% endblock %}
{% block content %}
    <div id="marquee" style="background: #212121;color:#ffffff;">
    <marquee style="color: white">
        {% for ch in error %}
            {% if ch.warn %}
                   &#10148; {{ ch.event_name }} : {{ ch.warn }}
            {% endif %}
        {% endfor %}
    </marquee>
    </div>
      <!-- Welcome Body Container -->
        <div class="container-fluid justify-content-center text-center" id="con1">
          <div id="particles-js"></div>
          <div class="col-12" id="info">
              <h1  id="open">
                  Welcome To <span style="color: #00f100;font-weight: 600;">Coding Club</span>
              </h1>
              <br>
              <h1 id="dept">
                  <span style="color: #00f100;font-weight: 600;">CSE DEPT. </span><a href="http://www.niet.co.in/" target="_blank" style="text-decoration: none;">NIET</a>
              </h1>
              <br>
                  <h1 id="place">
                    Gr. NOIDA
              </h1>
              <br>
              <a  href="#con2">
                <button class="btn btn-primary" id="btn1">About Us</button>
              </a>
        </div>
        </div>
        <!-- welcome body Ends -->
        <!-- About Body Starts -->
            <div class="container"  id="con2">
        <div class="row text-center justify-content-center" id="pad">
            <div class="col-lg-12">
                <h1>About Us</h1>
            </div>
        </div>
          <div class="row text-center" id="row1">
            <div class="col-lg-6" style="padding-top: 2rem;" id="r1">
              <h1 class="text-center head">CSE DEPT</h1><br>
              <p>
                  The Department of Computer Science and Engineering at NIET is renowned for its cutting edge research and imparting state-of-the-art education. The department attracts the bright students and faculty members.


              </p>
            </div>
           <div class="col-lg-6" style="padding-top: 2rem;" id="r2">
              <h1 class="text-center head">DEPT MISSION</h1><br>
                <p>To provide life-long learning environment to strengthen core competencies, innovation, problem-solving skills, ethical values and social responsibility.
                <br>To establish industry institute interaction and collaborations to prepare the students to adopt corporate culture with leadership and managerial skills.
                </p>
            </div>
          </div>
          <div class="row text-center" id="row2">
            <div class="col-lg-6" style="padding-top: 2rem;" id="r2">
              <h1 class="text-center head">CSE DEPT</h1><br>
                <p>
                    To become a prominent department of technical excellence in the field of computing and information system, providing an intellectual, innovative, and inspirational environment to produce competent professionals of the highest ethics equipped with future skills, research potential and attitude to create startups for society.
              </p>
            </div>
           <div class="col-lg-6" style="padding-top: 2rem;" id="r1">
              <h1 class="text-center head">CODING CLUB</h1><br>
                <p>
                    Our Club is dedicated to motivate Students of not only CSE department but of all departments towards the programming. This is 21st century and we can say it more or less the age of programming, our club is dedicated to provide help and platform to students to show up their programming skills by organising competitive events and Required Workshops.
                </p>
            </div>
          </div>
        </div>
        <!-- About Body Ends -->
        <!-- Get In Touch Icons -->
        <div class="container justify-content-center" style="display:flex;align-items: center;">
          <a href="https://www.instagram.com/shelendra_220/" target="_blank">
            <i class="fab fa-instagram" id="insta" aria-hidden="true"></i>
          </a>
          <a href="https://www.github.com/shelendravashishtha2/" target="_blank">
            <i class="fa fa-github" id="git" aria-hidden="true"></i>
          </a>
          <a href="https://www.linkedin.com/in/shelendra-vashishtha-246169184/" target="_blank">
            <i class="fa fa-linkedin-square" id="link" aria-hidden="true"></i>
          </a>
          <a href="https://wa.me/919012008071" target="_blank">
            <i class="fa fa-whatsapp" id="whats" aria-hidden="true"></i>
          </a>
        </div>
        <!-- Icon Container Ends -->
        <!-- Copyright  -->
        <div class="container-fluid text-center justify-item-center align-item-center" id="summary">
        <div class="row justify-content-center align-items-center" id="cont">
            <div class="col-md-12 justify-content-center align-items-center" id="contact">
                <h1 style="color: greenyellow;">Contact Us</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                <h3>
                    First Field
                </h3>
                <h5>
                    First Person
                </h5>
                <p>
                    <a href="https://www.instagram.com/shelendra_220/" target="_blank">
                         <i class="fab fa-instagram" id="insta" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.github.com/shelendravashishtha2/" target="_blank">
                        <i class="fa fa-github" id="git" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.linkedin.com/in/shelendra-vashishtha-246169184/" target="_blank">
                        <i class="fa fa-linkedin-square" id="link" aria-hidden="true"></i>
                    </a>
                    <a href="https://wa.me/919012008071" target="_blank">
                        <i class="fa fa-whatsapp" id="whats" aria-hidden="true"></i>
                    </a>
                </p>
            </div>
            <div class="col-md-4">
                <h3>
                    Second Field
                </h3>
                <h5>
                    Second Person
                </h5>
                <p>
                    <a href="https://www.instagram.com/shelendra_220/" target="_blank">
                         <i class="fab fa-instagram" id="insta" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.github.com/shelendravashishtha2/" target="_blank">
                        <i class="fa fa-github" id="git" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.linkedin.com/in/shelendra-vashishtha-246169184/" target="_blank">
                        <i class="fa fa-linkedin-square" id="link" aria-hidden="true"></i>
                    </a>
                    <a href="https://wa.me/919012008071" target="_blank">
                        <i class="fa fa-whatsapp" id="whats" aria-hidden="true"></i>
                    </a>
                </p>
            </div>
            <div class="col-md-4">
                <h3>
                     Third Field
                </h3>
                <h5>
                    Third Person
                </h5>
                <p>
                    <a href="https://www.instagram.com/shelendra_220/" target="_blank">
                         <i class="fab fa-instagram" id="insta" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.github.com/shelendravashishtha2/" target="_blank">
                        <i class="fa fa-github" id="git" aria-hidden="true"></i>
                    </a>
                    <a href="https://www.linkedin.com/in/shelendra-vashishtha-246169184/" target="_blank">
                        <i class="fa fa-linkedin-square" id="link" aria-hidden="true"></i>
                    </a>
                    <a href="https://wa.me/919012008071" target="_blank">
                        <i class="fa fa-whatsapp" id="whats" aria-hidden="true"></i>
                    </a>
                </p>
            </div>
        </div>
    </div>
        <div class="container justify-content-center text-center" id="cpy" style="color:#ffffff;">
          &#169; Designed and Developed By : Shelendra Vashishtha
        </div>
        <script type="text/javascript" src="{% static 'javascript/particles.js'%}"></script>
        <script type="text/javascript" src="{% static 'javascript/app.js' %}"></script>
{% endblock %}

form/templates/form/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
           CSE Club |  {% block title %}{% endblock %}
        </title>
        <link rel="icon" href="https://image.freepik.com/free-vector/futuristic-user-interface-concept_1284-37228.jpg" type="image/gif" sizes="16x16">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Yeon Sung' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/base.css' %}">
    {% block stysheet %}{% endblock %}
<!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,300,400,700&amp;display=swap" rel="stylesheet">
  <script src="https://kit.fontawesome.com/8ab3072a6a.js"></script><link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/latest/css/free.min.css" media="all"><link rel="stylesheet" href="https://kit-free.fontawesome.com/releases/latest/css/free-v4-shims.min.css" media="all">

    </head>
    <style>
    {% block style %}{% endblock %}
    </style>
    <body onload="myfunction();">
    <div id="loading"></div>
      <!-- bootstrap navbar -->
       {% block nav %}{% endblock %}
            <a class="navbar-brand text-center"  href="#" style="color: blueviolet !important;"><img src="{% static 'images/programming.png' %}" style="margin-right: 10px;" height="34px" width="34px" alt="">    CSE Coding Club</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li  class="nav-item active">
                  <a class="nav-link" href="{% url 'form:homepage' %}">Home<span class="sr-only">(current)</span></a>
                </li>
                {% if 'register' in avail %}
                    <li class="nav-item">
                        <a href="{% url 'form:register' %}" class="nav-link">Register</a>
                    </li>
                {% endif %}
                {% if 'event' in avail %}
                    <li class="nav-item">
                        <a href="{% url 'form:event' %}" class="nav-link">Events</a>
                    </li>
                {% endif %}
                {% if 'blog' in avail %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'form:blog' %}">Suggestions</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="https://shelendra.pythonanywhere.com/csed/" target="_blank">Other Sites</a>
                </li>
              </ul>
            </div>
        </nav>
      <!-- navbar ends -->
    {% block content %}{% endblock %}
    <script>
        var preloader=document.getElementById('loading');
        function myfunction()
        {
            preloader.style.display="none";
        }
    </script>
    </body>
</html>

form/templates/form/blog.html
{% extends 'form/base.html' %}
{% load static %}
{% block title %}
    Suggestion
{% endblock %}
{% block stysheet %}<link rel="stylesheet" type="text/css" href="{% static 'stylesheets/suggestion.css' %}">{% endblock %}
{% block nav %}<nav class="navbar fixed-top navbar-expand-md navbar-dark" style="background: #181818 !important;">{% endblock %}
{% block content %}
<div class="message text-center text-capitalize" style="color: #ffffff;background: #0077b5;width: 100%">
        {% if message %}
           {{ message }}
        {% endif %}
        </div>
        <br>
        <br>
        <br>
        <br>
    <div id="con1">
    <br>
        <br>
        <center>
            <h1 style="color: #333333;user-select: none;">
                Make Your Suggestions
            </h1>
        </center>
        <br>
        <div id="myform" class="justify-content-center align-content-center">
        <div class="form-group">
        <form method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.as_p }}
        </div>
        <div class="form-group">
            <br>
           <center><input type="submit" class="btn btn-primary" id="btn1" name="Submit" value="Register Here"></center>
        </div>
        </form>
        </div>
        </div>
    </div>
    <br>
    <!-- Form Ends -->
            <div class="container-fluid justify-content-center" style="display:flex;align-items: center;">
          <a href="https://www.instagram.com/shelendra_220/" target="_blank">
            <i class="fab fa-instagram" id="insta" aria-hidden="true"></i>
          </a>
          <a href="https://www.github.com/shelendravashishtha2/" target="_blank">
            <i class="fa fa-github" id="git" aria-hidden="true"></i>
          </a>
          <a href="https://www.linkedin.com/in/shelendra-vashishtha-246169184/" target="_blank">
            <i class="fa fa-linkedin-square" id="link" aria-hidden="true"></i>
          </a>
          <a href="https://wa.me/919012008071" target="_blank">
            <i class="fa fa-whatsapp" id="whats" aria-hidden="true"></i>
          </a>
        </div>
        <!-- Icon Container Ends -->
        <!-- Copyright  -->
        <div class="container-fluid justify-content-center text-center" id="cpy" style="color:#ffffff;">
          &#169; Developed By : Shelendra Vashishtha
        </div>
{% endblock %}

form/templates/form/download.html
{% extends "form/base.html" %}
{% load static %}
{% block title %}Download Data{% endblock %}
{% block stysheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'stylesheets/download.css' %}">
{% endblock %}
{% block nav %}<nav class="navbar navbar-expand-lg navbar-dark" style="background: #181818 !important;">{% endblock %}
{% block content %}
<div id="con1" >
<br>
<br>
    <center>
        <h1>
            Download Student Data
        </h1>
    </center>
<br>
    <!-- Form start -->
    <div  id="myform">
        <form method="post">
        {%  csrf_token %}
        <div class="form-group text-center">
            <label for="inp">Event Code</label>
            <input type="text" class="form-control" id="inp" title="Enters Valid event code here" name="eve_code" placeholder="Enter Event Code" required>
        </div>
        <br>
        <div class="form-group">
           <center><input type="submit" class="btn btn-primary" id="btn1" name="Submit" value="Submit"></center>
        </div>
        </form>
    <br>
    <br>
    </div>
</div>
    <!-- Error Start-->
<div class="container-fluid justify-content-center text-center" >
        <div class="row">
            <div class="col-lg-12" style="color: red;">
                     {% if error %}
                        <p>{{ error }}</p>
                     {% endif %}
            </div>
        </div>
</div>
    <!-- Social Media Icons -->
<div class="container justify-content-center" style="display:flex;align-items: center;">
          <a href="https://www.instagram.com/shelendra_220/" target="_blank">
            <i class="fab fa-instagram" id="insta" aria-hidden="true"></i>
          </a>
          <a href="https://www.github.com/shelendravashishtha2/" target="_blank">
            <i class="fa fa-github" id="git" aria-hidden="true"></i>
          </a>
          <a href="https://www.linkedin.com/in/shelendra-vashishtha-246169184/" target="_blank">
            <i class="fa fa-linkedin-square" id="link" aria-hidden="true"></i>
          </a>
          <a href="https://wa.me/919012008071" target="_blank">
            <i class="fa fa-whatsapp" id="whats" aria-hidden="true"></i>
          </a>
</div>
    <!-- Developer Information -->
<section class="container-fluid" style="border-top:2px solid blueviolet;padding-top: 10px;" id="con2">
    <div class="row align-items-center">
        <div class="col-md-12 text-center">
            <p>&#169; Shelendra Vashishtha</p><p>&#169; Computer Science And Engineering</p>
        </div>
    </div>
</section>
{% endblock %}